GET http://localhost:5000/GitHub/

###

POST http://localhost:3500/v1.0/bindings/github-graphql-binding
Content-Type: application/json

{
  "data": {
  },
  "metadata": {
    "query": "query { viewer { name } }"
  },
  "operation": "query"
}

###

POST http://localhost:3500/v1.0/bindings/github-graphql-binding
Content-Type: application/json

{
  "data": {
  },
  "metadata": {
    "query": "query { viewer { name avatarUrl } }"
  },
  "operation": "query"
}
